[package]
org = "tharinduwe"
name = "simple_http_call"
version = "0.1.0"
distribution = "2201.8.5"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerina"
name = "http"
version = "2.10.14"
repository = "local"
