[package]
org = "tharinduwe"
name = "simple_http_call"
version = "0.1.0"
distribution = "2201.8.5"

[[dependency]]
org = "ballerinax"
name = "redis"
version = "2.6.0"

[build-options]
observabilityIncluded = true
